---
- hosts: webservers
  become: yes
  tasks:

  - name: Install nginx
    apt:
        name: nginx
        state: present
        update_cache: yes


  - name: Ensure nginx service is running and enabled
    systemd:
        name: nginx
        state: started
        enabled: yes

- hosts: databases
  become: yes
  tasks:   

   - name: Install MySQL
     apt:
       name: mysql-server
       state: present
       update_cache: yes
       
   - name: MySQL service
     systemd:
       name: mysql
       state: started
       enabled: yes
   
   - name: Get status
     command: systemctl status mysql
     register: mysql_status

   - name: MySQL status
     debug:
      var: mysql_status